spring:
  application:
    name: server
  datasource:
    url: jdbc:mysql://localhost/product_management?autoReconnect=true
    username: config
    password: config
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
  http:
    response:
      tracing-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  description: default
  address: localhost
  request-protocol: http
  port: 8080
contact:
  name: Yassin MELLOUKI
  email: yassin.mellouki.j@gmail.com
info:
  title: Product management
  version: 0.0.1-SNAPSHOT
  description: Product management application.
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost/product_management?autoReconnect=true
    username: config
    password: config
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
  http:
    response:
      tracing-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  description: prod
  address: localhost
  request-protocol: http
  port: 8080
contact:
  name: Yassin MELLOUKI
  email: yassin.mellouki.j@gmail.com
info:
  title: Product management
  version: 0.0.1-SNAPSHOT
  description: Product management application.
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: preprod
  datasource:
    url: jdbc:mysql://localhost/product_management?autoReconnect=true
    username: config
    password: config
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
  http:
    response:
      tracing-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  description: preprod
  address: localhost
  request-protocol: http
  port: 8080
contact:
  name: Yassin MELLOUKI
  email: yassin.mellouki.j@gmail.com
info:
  title: Product management
  version: 0.0.1-SNAPSHOT
  description: Product management application.
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost/product_management?autoReconnect=true
    username: config
    password: config
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
  http:
    response:
      tracing-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  description: dev
  address: localhost
  request-protocol: http
  port: 8080
contact:
  name: Yassin MELLOUKI
  email: yassin.mellouki.j@gmail.com
info:
  title: Product management
  version: 0.0.1-SNAPSHOT
  description: Product management application.
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost/product_management?autoReconnect=true
    username: config
    password: config
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
  http:
    response:
      tracing-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  description: local
  address: localhost
  request-protocol: http
contact:
  name: Yassin MELLOUKI
  email: yassin.mellouki.j@gmail.com
info:
  title: Product management
  version: 0.0.1-SNAPSHOT
  description: Product management application.
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html